### ISSUE TITLE
Unable to install due to bundle ID mismatch

### ISSUE THREAD

**Issue by chadwoodhead** [Balackburn/Apollo#12]
When I try to install via SideStore, I receive the following error:

```
"Apollo" could not be installed.
The bundle ID "com.christianselig.Apollo" does not match the one specified by the source ("com.foo.Apollo").
```

**Comment by Balackburn** [comment]
Hello could you try again? I forgot to change the bundle ID of the latest release this should be fixed now

**Comment by chadwoodhead** [comment]
That error is gone. However,  I'm now running into the error where I can't install the app because I can't register more than 10 App IDs and I only have 1 remaining. I had previously tried installing Apollo via a different method with SideStore and that used a bunch of my App IDs. That method also failed and the app was never installed so I can't delete the Apollo app to free up App IDs. I'm curious if you know a solution to this?

**Comment by chadwoodhead** [comment]
I got around the 10 App ID limit by creating a new apple ID. However, now when I try to install Apollo from your source I get the error "AFC was unable to manage files on the device".

**Comment by Balackburn** [comment]
Hello, install the no Extension version manually :

https://github.com/Balackburn/Apollo/releases/download/v1.15.11-1.0.9/NO-EXTENSIONS_Apollo-1.15.11_improvedcustomapi-1.0.9.ipa

**Comment by chadwoodhead** [comment]
Even with that version I still get "AFC was unable to manage files on the device".

**Comment by Balackburn** [comment]
I can’t do anything for that unfortunately wait for your app id to expire, otherwise try with Sideloadly or buy a developer cert

**Comment by lanceuppercut47** [comment]
> Hello, install the no Extension version manually :
> 
> 
> 
> https://github.com/Balackburn/Apollo/releases/download/v1.15.11-1.0.9/NO-EXTENSIONS_Apollo-1.15.11_improvedcustomapi-1.0.9.ipa

Is there any way to make the no extensions version available when adding via the Sources tab too?  

I don't think any of the extensions actually does anything anyway so it's a waste of App IDs that I then can't use for other apps.

**Comment by Balackburn** [comment]
Sorry but I am not going to create a separate source for that, it’s open source so you can create your own, fork this repo and edit the script to choose the NO-EXTENSION file
